
export const FUN_FACTS_AND_JOKES = [
    "I tried to write a joke about WiFi… but I lost the connection. 📶😐",
    "I’m reading about glue… I’m stuck on chapter one. 🧴😬",
    "I told my pillow a secret… it stayed mute. 🛏️😶",
    "I made a joke about bread… it was crumby. 🍞😐",
    "I tried to play hide and seek… but I’m too easy to find. 🙃😬",
    "I told my shoe a joke… no reaction. 👟😐",
    "I made a joke about elevators… it had its ups and downs. 🛗😶",
    "I tried to laugh quietly… failed. 😭😐",
    "I made a joke about calendars… it was dated. 📅😬",
    "I don’t trust stairs… they’re always up to something. 🪜😳",
    "I wanted a joke about clouds… but it went over your head. ☁️😐",
    "I told my pen to stop… it kept drawing attention. 🖊️😬",
    "I tried to be funny once… it didn’t work. 😶‍🌫️😐",
    "I asked my clock for advice… it just ticked. ⏰😶",
    "I made a joke about soap… it was clean. 🧼😬",
    "I tried a joke about plants… it didn’t grow on me. 🌱😐",
    "My joke about math… didn’t add up. ➕😬",
    "I tried to catch a cold… now I have one. 🤧😐",
    "I made a joke about ice… it was pretty cool. 🧊😶",
    "I wrote a joke about paper… it folded under pressure. 📄😬",
    "I tried to joke about coffee… too bitter. ☕😐",
    "I made a joke about batteries… it didn’t charge. 🔋😶",
    "I told my phone a joke… it froze. 📱😬",
    "My joke about doors… didn’t open well. 🚪😐",
    "I made a joke about pizza… it was cheesy. 🍕😳",
    "Did you know honey never spoils? Archaeologists found edible honey in ancient tombs. 🍯",
    "Did you know octopuses have three hearts? 🐙",
    "Did you know bananas are berries, but strawberries aren’t? 🍌🍓",
    "Did you know a day on Venus is longer than its year? 🪐",
    "Did you know sharks are older than trees? 🦈🌲",
    "Did you know wombat poop is cube-shaped so it doesn’t roll away? 🟫",
    "Did you know your brain uses ~20% of your body’s energy even when resting? 🧠",
    "A group of flamingos is called a 'flamboyance'.",
    "The inventor of the frisbee was turned into a frisbee after he died.",
    "A single cloud can weigh more than 1 million pounds.",
    "A bolt of lightning is five times hotter than the surface of the sun.",
    "The unicorn is the national animal of Scotland.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "There are more trees on Earth than stars in the Milky Way galaxy.",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
    "A crocodile cannot stick its tongue out.",
    "It is impossible for most people to lick their own elbow.",
    "A shrimp's heart is in its head.",
    "A group of owls is called a parliament.",
    "A jiffy is an actual unit of time: 1/100th of a second.",
    "The 100 folds in a chef's hat represent 100 ways to cook an egg.",
    "The human nose can remember 50,000 different scents.",
    "Hot water will turn into ice faster than cold water.",
    "The fingerprints of a koala are so indistinguishable from humans that they have on occasion been confused at a crime scene."
];
